server.port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: LOAD-TEST
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#  datasource:
#    url: jdbc:postgresql://localhost:5432/cwm_import_validation_db
#    username: postgres
#    password: postgres
#    initialization-mode: always
  profiles:
    active: default