server.port: 8090
camunda.bpm.admin-user:
  id: admin
  password: admin
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: LOAD-TEST
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  profiles:
    active: kafka