package com.example.workflow.api;

import org.springframework.http.*;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

import java.net.InetSocketAddress;
import java.net.URI;
import java.util.Collections;

@RestController
public class ErmisProxy {

//    final static String URL = "https://SIT03.toldsystemet.ccta.dk/v1/business-rules/templates";
    final static String URL = "http://127.128.144.238:8080/ruleGroups/template/validateDeclarationAcceptanceDateEntryInDeclarantRecordsRelationsRS";

    @GetMapping("/v1/ref/data")
    public String proxyReferenceData(){
        System.out.println("Initiating request");

        RestTemplate restTemplate = new RestTemplate();
        HttpEntity<String> entity = new HttpEntity<>(getHeaders());
        ResponseEntity<String> response = restTemplate.exchange(URL, HttpMethod.GET, entity, String.class);

        System.out.println("Response: " + response);
        return "Done";
    }

    private HttpHeaders getHeaders(){
        HttpHeaders headers = new HttpHeaders();
//        headers.setBearerAuth(token);
        headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
        return headers;
    }

    private final static String token = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJISUxsQUtOcU92eU5UR0liRjgwSmZxT3RlSi0wOG04MkFFUmJxUXlCLWlBIn0.eyJleHAiOjE2NTA5NjI4MTQsImlhdCI6MTY1MDk1OTIxNCwianRpIjoiMDA3Mzc0Y2QtNzg1ZC00YTM0LTg4YzMtYmQ3OTI5N2RkY2ZkIiwiaXNzIjoiaHR0cHM6Ly9zaXQwMy50b2xkc3lzdGVtZXQuY2N0YS5kay9hdXRoL3JlYWxtcy9jd20iLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiYjE2OGI4ZjQtZDk1ZC00OGQxLTgzNTctZDU4MjExY2YwOWMzIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaW1wb3J0LXdlYi11aSIsInNlc3Npb25fc3RhdGUiOiJmZDNhMmUwNS05Zjc5LTRlYWMtOWZkYS1kZTUzZGI5OGYzMmMiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIlZpZXdTeXN0ZW1QYXJhbWV0ZXJBZG1pbiIsIlZpZXdCdXNpbmVzc1J1bGVVc2VyIiwiSGFuZGxlRXh0ZXJuYWxseVVzZXIiLCJDb250cm9sVXNlciIsIlZpZXdNZXNzYWdlU3RvcmVVc2VyIiwiVmlld0RlY2xhcmF0aW9uVXNlciIsIkNyZWF0ZURlY2xhcmF0aW9uVXNlciIsIkNvdmVyYWdlVXNlciIsIlN1cGVydmlzb3JVc2VyIiwiUmVwb3J0VXNlciIsIkF1dGhvcml6YXRpb25NYXBwaW5nQWRtaW4iLCJVcGRhdGVCdXNpbmVzc1J1bGVVc2VyIiwiTW9kaWZ5RGVjbGFyYXRpb25Vc2VyIiwiQ3VzdG9tc09mZmljZVVzZXIiLCJvZmZsaW5lX2FjY2VzcyIsIkFkZFJlbWFya1VzZXIiLCJDdXN0b21zUG9zaXRpb25Vc2VyIiwidW1hX2F1dGhvcml6YXRpb24iLCJDdXN0b21zRGVidFVzZXIiLCJVcGRhdGVTeXN0ZW1QYXJhbWV0ZXJBZG1pbiIsIkNyZWF0ZVZlcmJhbERlY2xhcmF0aW9uVXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctdXNlcnMiLCJxdWVyeS1ncm91cHMiLCJxdWVyeS11c2VycyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiZmQzYTJlMDUtOWY3OS00ZWFjLTlmZGEtZGU1M2RiOThmMzJjIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJyb2xlcyI6WyJWaWV3U3lzdGVtUGFyYW1ldGVyQWRtaW4iLCJWaWV3QnVzaW5lc3NSdWxlVXNlciIsIkhhbmRsZUV4dGVybmFsbHlVc2VyIiwiQ29udHJvbFVzZXIiLCJWaWV3TWVzc2FnZVN0b3JlVXNlciIsIlZpZXdEZWNsYXJhdGlvblVzZXIiLCJDcmVhdGVEZWNsYXJhdGlvblVzZXIiLCJDb3ZlcmFnZVVzZXIiLCJTdXBlcnZpc29yVXNlciIsIlJlcG9ydFVzZXIiLCJBdXRob3JpemF0aW9uTWFwcGluZ0FkbWluIiwiVXBkYXRlQnVzaW5lc3NSdWxlVXNlciIsIk1vZGlmeURlY2xhcmF0aW9uVXNlciIsIkN1c3RvbXNPZmZpY2VVc2VyIiwib2ZmbGluZV9hY2Nlc3MiLCJBZGRSZW1hcmtVc2VyIiwiQ3VzdG9tc1Bvc2l0aW9uVXNlciIsInVtYV9hdXRob3JpemF0aW9uIiwiQ3VzdG9tc0RlYnRVc2VyIiwiVXBkYXRlU3lzdGVtUGFyYW1ldGVyQWRtaW4iLCJDcmVhdGVWZXJiYWxEZWNsYXJhdGlvblVzZXIiXSwiZ3JvdXBzIjpbIlZpZXdTeXN0ZW1QYXJhbWV0ZXJBZG1pbiIsIlZpZXdCdXNpbmVzc1J1bGVVc2VyIiwiSGFuZGxlRXh0ZXJuYWxseVVzZXIiLCJDb250cm9sVXNlciIsIlZpZXdNZXNzYWdlU3RvcmVVc2VyIiwiVmlld0RlY2xhcmF0aW9uVXNlciIsIkNyZWF0ZURlY2xhcmF0aW9uVXNlciIsIkNvdmVyYWdlVXNlciIsIlN1cGVydmlzb3JVc2VyIiwiUmVwb3J0VXNlciIsIkF1dGhvcml6YXRpb25NYXBwaW5nQWRtaW4iLCJVcGRhdGVCdXNpbmVzc1J1bGVVc2VyIiwiTW9kaWZ5RGVjbGFyYXRpb25Vc2VyIiwiQ3VzdG9tc09mZmljZVVzZXIiLCJvZmZsaW5lX2FjY2VzcyIsIkFkZFJlbWFya1VzZXIiLCJDdXN0b21zUG9zaXRpb25Vc2VyIiwidW1hX2F1dGhvcml6YXRpb24iLCJDdXN0b21zRGVidFVzZXIiLCJVcGRhdGVTeXN0ZW1QYXJhbWV0ZXJBZG1pbiIsIkNyZWF0ZVZlcmJhbERlY2xhcmF0aW9uVXNlciJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbi1hcHAifQ.U4vGXI8zAdODG8hoKq0n3HiQQ-RzgTonHJikU14873SJLMPUAnSHQNN9qMS7akyGcd1-eMg6v8aUaLPZamsVdwnC4yb8LSyRwz6T9RY9iWKvceKlaGtwdZCPPUTgLkMbbJPEKuLy-0My_QvK9BPsqV0q-2Jpl0YCPqOzQipYShFokBvDR7eW51e5S2kl9xo5Asb-b_dIaY8BvDRgNob99PH9v4NpfGa88wMfcZld_zC4ciPxl8h4rNbZtBYkwQJdjl81_gkhN2MH531BYUREmkmCfUIRWLg6jX3cH5wTi4e7TAr3FQwfOrkHeZ_ZXipefNYDqtTky_szh1vjwqXrbjxrcIVDgd5YLbYxLuVPllGhapMGNnJQ-WQ4M2T3JEUXpKrD0udzEU50chiokJPX-x986L67em1ru29QEDHCKBDKVic_Dlgo4MHCvtidLed9xZ3cuH9eTmzjpHb1kSnGUSTC4-G0ZMlaxdzRKH9XIZkQiqmNrZFm5zASii5qM03XscJsA0wYHai2BCZv1ja3gg3kSr4FOllHJ0WHjp5vm2Vb_1F6KCmaG24CRm_BLDSJs1jBOPzBDmieo3kO65n865km0auOrdb1Fs6TT_f3Nx_VoZcTSdhCWfaqEaHZub2IFgR7VH-JakZyq9mNksAYKfxVHnKhwNGHMrSrCRLSELk";
}
